volumes:
  mssqlvolume:
    name: sqlserver-mssql-vl

services:
  my-mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver-mssql
    user: root
    restart: always
    hostname: mssql
    environment:
      MSSQL_SA_PASSWORD: 'Password123' #Thiết lập password
      ACCEPT_EULA: 'Y'
      # Express: 
    volumes:
      - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
      # - ./bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"
